sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker version

  - docker build --no-cache -t m9rco/etcd:3.3.13 -f 3.3.13/Dockerfile 3.3.13/
  - docker-compose -f 3.3.13/docker-compose.yml up -d

  - docker build --no-cache -t m9rco/etcd:2.0.10 -f 2.0.10/Dockerfile 2.0.10/
  - docker-compose -f 2.0.10/docker-compose.yml up -d


script:
  - docker exec 3313_etcd_1 sh -c "etcdctl -v""
  - docker exec 2010_etcd_1 sh -c "etcdctl -v""
