#!/bin/bash

# For more information regarding bash shells, see:
# https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files

#
# This script is sourced before '/usr/share/entrypoint.sh'
# Look in '/usr/share/entrypoint.sh' for examples of setting
# environment variables in the environment immediately
# after entering the container
# 

echo
echo "Welcome $(whoami), from '/etc/bashrc'"
echo "Sourced by: $0."
echo

# colorized pretty print "username pwd $ "
export PS1='\[\e]0;\u \w\a\]\[\033[01;32m\]\u \[\033[01;34m\]\w \$\[\033[00m\] '
